import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from 'next/image';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faSquareInstagram, faSquareFacebook, faSquareWhatsapp } from '@fortawesome/free-brands-svg-icons';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className=" relative ">
          <div className="w-full flex flex-wrap justify-between p-5 mt-2 z-10">
            <Image className="mt-1 ml-10" width={150} height={100} alt="IRSA" src={'/images/img1.png'}></Image>
            <div className="mt-5 flex flex-wrap gap-20">
                <div className="flex flex-wrap gap-20 mt-1">
                  <a href="" key="exames"> Exames </a>
                  <a href="" key="sobre"> Sobre </a>
                  <a href="" key="convenios"> Convênios</a>
                  <a href="" key="irsa-solidario"> IRSA Solidário</a>
                </div>
                <div className="flex flex-wrap gap-3 text-sky-900">
                  <FontAwesomeIcon width={30} height={30} icon={faSquareInstagram} />
                  <FontAwesomeIcon width={30} height={30} icon={faSquareFacebook} />
                  <FontAwesomeIcon width={30} height={30} icon={faSquareWhatsapp} />
                </div>
            </div>
          </div>
        </div>

        {children}
      </body>
    </html>
  );
}